title: 'Dance East'
updated_by: 5b72ad31-9613-4471-9564-e28d5005ecc0
updated_at: 1643387409
blueprint: organisers
logo: danceeastimages/logo-dance-east-inverse.png
link: 'https://www.danceeast.co.uk/'
