title: 'Festival Bridge'
updated_by: a720ec70-17d4-4534-b9e4-f0e078465928
updated_at: 1727697106
blueprint: organisers
logo: miscellaneous/logo-festival-bridge.png
link: 'https://nnfestival.org.uk/schools-and-communities/festival-bridge/'
