title: 'Festival Bridge'
updated_by: 5b72ad31-9613-4471-9564-e28d5005ecc0
updated_at: 1643387461
blueprint: organisers
logo: miscellaneous/logo-festival-bridge.png
link: 'https://nnfestival.org.uk/festival-bridge/'
