title: 'Suffolk Art Link'
updated_by: 5b72ad31-9613-4471-9564-e28d5005ecc0
updated_at: 1643387365
blueprint: organisers
logo: suffolkartlinkimages/logo-suffolk-artlink.png
link: 'https://www.suffolkartlink.org.uk/'
